### ISSUE TITLE
Fotografía en edición de los datos del bus

### ISSUE THREAD

**Issue by YadiraAllauca** [Eldinosaur/ProyectoDASBusesOficinista#18]
En el formulario de editar la información del bus, es preferible que se muestre la imagen en vez de solo el url
![image](https://github.com/Eldinosaur/ProyectoDASBusesOficinista/assets/94416577/50a54e29-3321-42a9-95cb-79d3cf10d035)

**Comment by Eldinosaur** [comment]
Se realizó el cambio segun lo solicitado
@YadiraAllauca solicito autorización para fusión con rama develop
- Código fuente

![image](https://github.com/Eldinosaur/ProyectoDASBusesOficinista/assets/82054019/3933bcb2-0e2c-4197-9c26-2766ab00be1c)

- Visualización

![image](https://github.com/Eldinosaur/ProyectoDASBusesOficinista/assets/82054019/3a10f344-61c9-425f-9f22-1fee42bdd201)

**Comment by YadiraAllauca** [comment]
Se cumplió con lo solicitado, se puede efectuar la fusión con develop
